package config

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"
)

type Config struct {
	// Database
	DatabaseURL string

	// Server
	Port        string
	AppURL      string
	CORSOrigins string

	// PublicDir: if this directory exists, rapibase serves it at / with an
	// SPA fallback (same-origin frontend hosting, PocketBase-style). The
	// admin dashboard always lives under the reserved /_/ path.
	PublicDir string

	// Auth
	JWTSecret     string
	AdminEmail    string
	AdminPassword string

	// API Keys
	AnonKey    string
	ServiceKey string

	// Token Expiration
	JWTExpiry     time.Duration
	RefreshExpiry time.Duration

	// Access Log
	AccessLogEnabled       bool
	AccessLogRetentionDays int

	// Public signup (POST /api/v1/auth/signup)
	SignupEnabled        bool
	SignupAllowedDomains []string

	// SMTP
	SMTPHost     string
	SMTPPort     string
	SMTPUser     string
	SMTPPass     string
	SMTPFrom     string
	SMTPFromName string

	// Auth Redirects (for third-party apps)
	AuthRedirectURL string // Where to redirect after email verification, magic link, etc.

	// Storage (MinIO)
	StorageEnabled   bool
	StorageEndpoint  string
	StorageAccessKey string
	StorageSecretKey string
	StorageUseSSL    bool
	StoragePublicURL string

	// Realtime (WebSocket-based change-data + broadcast + presence + rpc)
	RealtimeEnabled         bool
	RealtimeSlotName        string
	RealtimePublicationName string

	// RealtimeLockKey is the bigint passed to pg_try_advisory_lock for
	// leader election. Set to a non-zero value when running multiple
	// rapibase instances against the same Postgres so only one node
	// consumes the replication slot. Zero (default) means single-node.
	RealtimeLockKey int64

	// Functions: user-provided TS/JS running in an embedded interpreter
	// (HTTP endpoints, cron schedules and queue workers).
	FunctionsEnabled bool
	FunctionsDir     string

	// Social login (OAuth authorization code). A provider is enabled when
	// both its client id and secret are set. Callback URL to register at
	// the provider: {APP_URL}/api/v1/auth/oauth/{provider}/callback
	OAuthGoogleClientID       string
	OAuthGoogleClientSecret   string
	OAuthGitHubClientID       string
	OAuthGitHubClientSecret   string
	OAuthFacebookClientID     string
	OAuthFacebookClientSecret string
}

func Load() *Config {
	return &Config{
		// Database
		DatabaseURL: getEnv("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/rapibase?sslmode=disable"),

		// Server
		Port:        getEnv("PORT", "8080"),
		AppURL:      getEnv("APP_URL", "http://localhost:8080"),
		CORSOrigins: getEnv("CORS_ORIGINS", "*"),
		PublicDir:   getEnv("PUBLIC_DIR", "./rb_public"),

		// Auth — secrets are finalized by ResolveSecrets() after the DB
		// is up: blank values are generated + persisted, weak known
		// defaults are rejected. We deliberately do NOT default these to
		// the example values shipped in the repo.
		JWTSecret:     getEnv("JWT_SECRET", ""),
		AdminEmail:    getEnv("ADMIN_EMAIL", "admin@rapibase.local"),
		AdminPassword: getEnv("ADMIN_PASSWORD", ""),

		// API Keys — resolved/generated by ResolveSecrets().
		AnonKey:    getEnv("ANON_KEY", ""),
		ServiceKey: getEnv("SERVICE_KEY", ""),

		// Token Expiration
		JWTExpiry:     parseDuration(getEnv("JWT_EXPIRY", "1h"), time.Hour),
		RefreshExpiry: parseDuration(getEnv("REFRESH_EXPIRY", "7d"), 7*24*time.Hour),

		// Access Log
		AccessLogEnabled:       getEnvBool("ACCESS_LOG_ENABLED", true),
		AccessLogRetentionDays: int(getEnvInt64("ACCESS_LOG_RETENTION_DAYS", 30)),

		// Public signup — OFF by default. Admins create app users via the
		// dashboard / SERVICE_KEY regardless of this flag.
		SignupEnabled:        getEnvBool("AUTH_SIGNUP_ENABLED", false),
		SignupAllowedDomains: parseCSVLower(getEnv("AUTH_SIGNUP_ALLOWED_DOMAINS", "")),

		// SMTP
		SMTPHost:     getEnv("SMTP_HOST", ""),
		SMTPPort:     getEnv("SMTP_PORT", "587"),
		SMTPUser:     getEnv("SMTP_USER", ""),
		SMTPPass:     getEnv("SMTP_PASS", ""),
		SMTPFrom:     getEnv("SMTP_FROM", ""),
		SMTPFromName: getEnv("SMTP_FROM_NAME", "RapiBase"),

		// Auth Redirects - defaults to APP_URL if not set
		AuthRedirectURL: getEnv("AUTH_REDIRECT_URL", ""),

		// Storage (MinIO)
		StorageEnabled:   getEnvBool("STORAGE_ENABLED", true),
		StorageEndpoint:  getEnv("STORAGE_ENDPOINT", "localhost:9000"),
		StorageAccessKey: getEnv("STORAGE_ACCESS_KEY", "minioadmin"),
		StorageSecretKey: getEnv("STORAGE_SECRET_KEY", "minioadmin"),
		StorageUseSSL:    getEnvBool("STORAGE_USE_SSL", false),
		StoragePublicURL: getEnv("STORAGE_PUBLIC_URL", "http://localhost:9000"),

		// Realtime
		RealtimeEnabled:         getEnvBool("REALTIME_ENABLED", true),
		RealtimeSlotName:        getEnv("REALTIME_SLOT_NAME", "rapibase"),
		RealtimePublicationName: getEnv("REALTIME_PUBLICATION_NAME", "rapibase_realtime"),
		RealtimeLockKey:         getEnvInt64("REALTIME_LOCK_KEY", 0),

		// Functions (TS/JS embebido: HTTP + cron + workers)
		FunctionsEnabled: getEnvBool("FUNCTIONS_ENABLED", true),
		FunctionsDir:     getEnv("FUNCTIONS_DIR", "./rb_functions"),

		// Login social
		OAuthGoogleClientID:       getEnv("OAUTH_GOOGLE_CLIENT_ID", ""),
		OAuthGoogleClientSecret:   getEnv("OAUTH_GOOGLE_CLIENT_SECRET", ""),
		OAuthGitHubClientID:       getEnv("OAUTH_GITHUB_CLIENT_ID", ""),
		OAuthGitHubClientSecret:   getEnv("OAUTH_GITHUB_CLIENT_SECRET", ""),
		OAuthFacebookClientID:     getEnv("OAUTH_FACEBOOK_CLIENT_ID", ""),
		OAuthFacebookClientSecret: getEnv("OAUTH_FACEBOOK_CLIENT_SECRET", ""),
	}
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return strings.TrimSpace(value)
	}
	return defaultValue
}

// SecretStore persists auto-generated secrets so they stay stable
// across restarts (zero-config: no manual key management). Implemented
// by *database.DB. Kept as an interface here so the config package does
// not depend on the database package.
type SecretStore interface {
	GetSecret(ctx context.Context, key string) (string, bool, error)
	SetSecret(ctx context.Context, key, value string) error
}

// weakSecrets are values shipped as examples/defaults in the public
// repo (and therefore known to any attacker). They must never reach a
// running deployment.
var weakSecrets = map[string]bool{
	"change-this-secret-in-production":       true,
	"rapibase-service-key-2024-admin-secret": true,
	"rapibase-anon-key-2024-public-access":   true,
	"admin123":                               true,
	"minioadmin":                             true,
}

func isWeakSecret(v string) bool { return weakSecrets[strings.TrimSpace(v)] }

// ResolveSecrets finalizes JWTSecret, AnonKey, ServiceKey and
// AdminPassword. Must be called after the database is migrated.
//
//   - A value explicitly provided via env that matches a known weak
//     default is a fatal misconfiguration (returns an error).
//   - A blank value is loaded from the secret store, or generated once
//     and persisted there, so restarts keep the same keys without any
//     manual step.
//
// It also emits non-fatal warnings for risky-but-not-secret settings
// (default MinIO credentials, wide-open CORS).
func (c *Config) ResolveSecrets(ctx context.Context, store SecretStore) error {
	fields := []struct {
		name     string
		ptr      *string
		storeKey string
		minLen   int
	}{
		{"JWT_SECRET", &c.JWTSecret, "jwt_secret", 32},
		{"ANON_KEY", &c.AnonKey, "anon_key", 24},
		{"SERVICE_KEY", &c.ServiceKey, "service_key", 24},
	}

	// First pass: validate every operator-provided secret and collect
	// ALL problems, so the operator fixes them in one go instead of
	// hitting them one container-restart at a time.
	var problems []string
	for _, f := range fields {
		val := strings.TrimSpace(*f.ptr)
		if val == "" {
			continue
		}
		if isWeakSecret(val) {
			problems = append(problems, fmt.Sprintf("  • %s is a known default/example value (public in the repo)", f.name))
		} else if len(val) < f.minLen {
			problems = append(problems, fmt.Sprintf("  • %s is too short (%d chars, need at least %d)", f.name, len(val), f.minLen))
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf(
			"refusing to start — weak or invalid secret(s):\n%s\n\n"+
				"Fix: give each a strong unique value, OR leave it BLANK in your env/.env so\n"+
				"rapibase generates a strong one automatically (persisted in the DB, stable\n"+
				"across restarts). This is a one-time step on this update.",
			strings.Join(problems, "\n"))
	}

	// Second pass: use the provided value, or load/generate a blank one.
	for _, f := range fields {
		if strings.TrimSpace(*f.ptr) != "" {
			*f.ptr = strings.TrimSpace(*f.ptr)
			continue
		}
		stored, ok, err := store.GetSecret(ctx, f.storeKey)
		if err != nil {
			return fmt.Errorf("read %s from secret store: %w", f.name, err)
		}
		if !ok {
			stored = generateSecret(32)
			if err := store.SetSecret(ctx, f.storeKey, stored); err != nil {
				return fmt.Errorf("persist generated %s: %w", f.name, err)
			}
			log.Printf("🔐 Generated %s (persisted; stable across restarts)", f.name)
		}
		*f.ptr = stored
	}

	// Never bootstrap the admin with a weak/empty password.
	if pw := strings.TrimSpace(c.AdminPassword); pw == "" || isWeakSecret(pw) {
		stored, ok, err := store.GetSecret(ctx, "admin_password")
		if err != nil {
			return fmt.Errorf("read admin password from secret store: %w", err)
		}
		if !ok {
			stored = generateSecret(18)
			if err := store.SetSecret(ctx, "admin_password", stored); err != nil {
				return fmt.Errorf("persist generated admin password: %w", err)
			}
			log.Printf("🔐 Generated initial admin password for %s (shown once): %s", c.AdminEmail, stored)
		}
		c.AdminPassword = stored
	}

	if isWeakSecret(c.StorageAccessKey) || isWeakSecret(c.StorageSecretKey) {
		log.Printf("⚠️  MinIO is using default credentials (minioadmin). Set STORAGE_ACCESS_KEY/STORAGE_SECRET_KEY to strong values and rotate the MinIO root user.")
	}
	if strings.TrimSpace(c.CORSOrigins) == "*" {
		log.Printf("⚠️  CORS_ORIGINS is '*' (any origin). Restrict it to your app's domain(s) in production.")
	}

	return nil
}

func generateSecret(n int) string {
	b := make([]byte, n)
	rand.Read(b)
	return base64.RawURLEncoding.EncodeToString(b)
}

func (c *Config) IsSMTPConfigured() bool {
	return c.SMTPHost != "" && c.SMTPUser != "" && c.SMTPPass != ""
}

func (c *Config) IsStorageEnabled() bool {
	return c.StorageEnabled && c.StorageEndpoint != "" && c.StorageAccessKey != "" && c.StorageSecretKey != ""
}

func getEnvBool(key string, defaultValue bool) bool {
	if value := os.Getenv(key); value != "" {
		return strings.ToLower(strings.TrimSpace(value)) == "true" || value == "1"
	}
	return defaultValue
}

// parseCSVLower splits a comma-separated env value into a trimmed,
// lower-cased, empty-free slice.
func parseCSVLower(s string) []string {
	var out []string
	for _, part := range strings.Split(s, ",") {
		if p := strings.ToLower(strings.TrimSpace(part)); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func getEnvInt64(key string, defaultValue int64) int64 {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return defaultValue
	}
	n, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return defaultValue
	}
	return n
}

// parseDuration parses duration strings like "1h", "24h", "7d", "30d"
func parseDuration(s string, defaultVal time.Duration) time.Duration {
	s = strings.TrimSpace(s)
	if s == "" {
		return defaultVal
	}

	// Handle days specially (not supported by time.ParseDuration)
	if strings.HasSuffix(s, "d") {
		days := strings.TrimSuffix(s, "d")
		var d int
		if _, err := strings.NewReader(days).Read([]byte{}); err == nil {
			for _, c := range days {
				if c >= '0' && c <= '9' {
					d = d*10 + int(c-'0')
				}
			}
			if d > 0 {
				return time.Duration(d) * 24 * time.Hour
			}
		}
		return defaultVal
	}

	duration, err := time.ParseDuration(s)
	if err != nil {
		return defaultVal
	}
	return duration
}
